# Change these first
owner: voxology-ai # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Voxology Agent Prod
    url: https://voxology-functions.azurewebsites.net/api/status
    logo: https://raw.githubusercontent.com/Voxology-ai/status/master/assets/vox-logo.svg
    headers:
      - "x-status-secret: $STATUS_SECRET_PROD"
  - name: Voxology Agent Dev
    url: https://voxology-functions-dev.azurewebsites.net/api/status
    logo: https://raw.githubusercontent.com/Voxology-ai/status/master/assets/vox-logo.svg
    headers:
      - "x-status-secret: $STATUS_SECRET"
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.voxology.ai
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/Voxology-ai/status/master/assets/vox-logo.svg
  name: Voxology Status
  introTitle: "**Voxology Status** - Service Health Dashboard"
  introMessage: Real-time monitoring of Voxology AI services and APIs. This page automatically updates to show the current operational status of our systems.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Voxology AI
      href: https://voxology.ai
  theme: light # Options: light, dark, night, ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
