# Change these first
owner: voxology-ai # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Voxology Agent Dev
    url: https://voxology-functions-dev.azurewebsites.net/api/status
    headers:
      - "x-status-secret: ${{ secrets.STATUS_SECRET }}"
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.voxology.ai
  baseUrl: /status
  logoUrl: https://github.com/Voxology-ai/status/blob/master/assets/logo.png
  name: Voxology Status
  introTitle: "**Voxology Status** - Service Health Dashboard"
  introMessage: Real-time monitoring of Voxology AI services and APIs. This page automatically updates to show the current operational status of our systems.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Voxology AI
      href: https://voxology.ai
  theme: ocean # Options: light, dark, night, ocean

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
